# Generated by Django 3.0.3 on 2020-03-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200318_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='building_flat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.ShipmentAddress'),
        ),
    ]
