# Generated by Django 3.0.3 on 2020-03-24 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200319_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentaddress',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.ShipmentAddress'),
        ),
    ]
