# Generated by Django 3.0.3 on 2020-03-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_shipmentaddress_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentaddress',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentaddress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile'),
        ),
    ]
