# Generated by Django 3.0.3 on 2020-03-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200330_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentaddress',
            name='profile',
        ),
    ]
