# Generated by Django 3.0.3 on 2020-03-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_shipmentaddress_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentaddress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile'),
        ),
    ]
