# Generated by Django 3.0.3 on 2020-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200302_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
