# Generated by Django 3.0.3 on 2020-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200302_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/img/logo-img.png', upload_to='products/<django.db.models.fields.CharField>/'),
        ),
    ]
