# Generated by Django 3.0.4 on 2020-08-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200326_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_blob',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
