# Generated by Django 3.0.4 on 2020-08-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200802_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
