# Generated by Django 3.0.4 on 2020-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_image_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/img/logo-img-light-green.png', upload_to='img/product'),
        ),
    ]
