# Generated by Django 3.0.4 on 2020-08-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200802_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_blob',
        ),
        migrations.AddField(
            model_name='product',
            name='image_binary',
            field=models.BinaryField(blank=True),
        ),
    ]
