# Generated by Django 3.0.4 on 2020-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200902_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/logo-img-light-green.png', upload_to='img/product/'),
        ),
    ]
