# Generated by Django 3.0.3 on 2020-03-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0011_auto_20200302_0947'),
        ('users', '0009_auto_20200319_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PAYONG', 'ONGOING PAYMENT'), ('PAYPRO', 'PAYMENT PROCESSED'), ('INPROG', 'IN PROGRESS'), ('SENT', 'SENT'), ('DELIV', 'DELIVERED')], default='NEW', max_length=6)),
                ('payment_status', models.CharField(choices=[('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='F', max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
                ('product', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
