# Generated by Django 3.0.3 on 2020-03-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200324_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
