# Generated by Django 3.0.3 on 2020-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200324_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('O', 'ONGOING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='O', max_length=6),
        ),
    ]
